opcodeTable1 = """
    <td><abbr title="No Operation">NOP</abbr></td>
    <td><abbr title="Load 16-bit immediate into BC">LD BC,nn</abbr></td>
    <td><abbr title="Save A to address pointed by BC">LD (BC),A</abbr></td>
    <td><abbr title="Increment 16-bit BC">INC BC</abbr></td>
    <td><abbr title="Increment B">INC B</abbr></td>
    <td><abbr title="Decrement B">DEC B</abbr></td>
    <td><abbr title="Load 8-bit immediate into B">LD B,n</abbr></td>
    <td><abbr title="Rotate A left with carry">RLC A</abbr></td>
    <td><abbr title="Save SP to given address">LD (nn),SP</abbr></td>
    <td><abbr title="Add 16-bit BC to HL">ADD HL,BC</abbr></td>
    <td><abbr title="Load A from address pointed to by BC">LD A,(BC)</abbr></td>
    <td><abbr title="Decrement 16-bit BC">DEC BC</abbr></td>
    <td><abbr title="Increment C">INC C</abbr></td>
    <td><abbr title="Decrement C">DEC C</abbr></td>
    <td><abbr title="Load 8-bit immediate into C">LD C,n</abbr></td>
    <td><abbr title="Rotate A right with carry">RRC A</abbr></td>
    <td><abbr title="Stop processor">STOP</abbr></td>
    <td><abbr title="Load 16-bit immediate into DE">LD DE,nn</abbr></td>
    <td><abbr title="Save A to address pointed by DE">LD (DE),A</abbr></td>
    <td><abbr title="Increment 16-bit DE">INC DE</abbr></td>
    <td><abbr title="Increment D">INC D</abbr></td>
    <td><abbr title="Decrement D">DEC D</abbr></td>
    <td><abbr title="Load 8-bit immediate into D">LD D,n</abbr></td>
    <td><abbr title="Rotate A left">RL A</abbr></td>
    <td><abbr title="Relative jump by signed immediate">JR n</abbr></td>
    <td><abbr title="Add 16-bit DE to HL">ADD HL,DE</abbr></td>
    <td><abbr title="Load A from address pointed to by DE">LD A,(DE)</abbr></td>
    <td><abbr title="Decrement 16-bit DE">DEC DE</abbr></td>
    <td><abbr title="Increment E">INC E</abbr></td>
    <td><abbr title="Decrement E">DEC E</abbr></td>
    <td><abbr title="Load 8-bit immediate into E">LD E,n</abbr></td>
    <td><abbr title="Rotate A right">RR A</abbr></td>
    <td><abbr title="Relative jump by signed immediate if last result was not zero">JR NZ,n</abbr></td>
    <td><abbr title="Load 16-bit immediate into HL">LD HL,nn</abbr></td>
    <td><abbr title="Save A to address pointed by HL, and increment HL">LDI (HL),A</abbr></td>
    <td><abbr title="Increment 16-bit HL">INC HL</abbr></td>
    <td><abbr title="Increment H">INC H</abbr></td>
    <td><abbr title="Decrement H">DEC H</abbr></td>
    <td><abbr title="Load 8-bit immediate into H">LD H,n</abbr></td>
    <td><abbr title="Adjust A for BCD addition">DAA</abbr></td>
    <td><abbr title="Relative jump by signed immediate if last result was zero">JR Z,n</abbr></td>
    <td><abbr title="Add 16-bit HL to HL">ADD HL,HL</abbr></td>
    <td><abbr title="Load A from address pointed to by HL, and increment HL">LDI A,(HL)</abbr></td>
    <td><abbr title="Decrement 16-bit HL">DEC HL</abbr></td>
    <td><abbr title="Increment L">INC L</abbr></td>
    <td><abbr title="Decrement L">DEC L</abbr></td>
    <td><abbr title="Load 8-bit immediate into L">LD L,n</abbr></td>
    <td><abbr title="Complement (logical NOT) on A">CPL</abbr></td>
    <td><abbr title="Relative jump by signed immediate if last result caused no carry">JR NC,n</abbr></td>
    <td><abbr title="Load 16-bit immediate into SP">LD SP,nn</abbr></td>
    <td><abbr title="Save A to address pointed by HL, and decrement HL">LDD (HL),A</abbr></td>
    <td><abbr title="Increment 16-bit HL">INC SP</abbr></td>
    <td><abbr title="Increment value pointed by HL">INC (HL)</abbr></td>
    <td><abbr title="Decrement value pointed by HL">DEC (HL)</abbr></td>
    <td><abbr title="Load 8-bit immediate into address pointed by HL">LD (HL),n</abbr></td>
    <td><abbr title="Set carry flag">SCF</abbr></td>
    <td><abbr title="Relative jump by signed immediate if last result caused carry">JR C,n</abbr></td>
    <td><abbr title="Add 16-bit SP to HL">ADD HL,SP</abbr></td>
    <td><abbr title="Load A from address pointed to by HL, and decrement HL">LDD A,(HL)</abbr></td>
    <td><abbr title="Decrement 16-bit SP">DEC SP</abbr></td>
    <td><abbr title="Increment A">INC A</abbr></td>
    <td><abbr title="Decrement A">DEC A</abbr></td>
    <td><abbr title="Load 8-bit immediate into A">LD A,n</abbr></td>
    <td><abbr title="Clear carry flag">CCF</abbr></td>
    <td><abbr title="Copy B to B">LD B,B</abbr></td>
    <td><abbr title="Copy C to B">LD B,C</abbr></td>
    <td><abbr title="Copy D to B">LD B,D</abbr></td>
    <td><abbr title="Copy E to B">LD B,E</abbr></td>
    <td><abbr title="Copy H to B">LD B,H</abbr></td>
    <td><abbr title="Copy L to B">LD B,L</abbr></td>
    <td><abbr title="Copy value pointed by HL to B">LD B,(HL)</abbr></td>
    <td><abbr title="Copy A to B">LD B,A</abbr></td>
    <td><abbr title="Copy B to C">LD C,B</abbr></td>
    <td><abbr title="Copy C to C">LD C,C</abbr></td>
    <td><abbr title="Copy D to C">LD C,D</abbr></td>
    <td><abbr title="Copy E to C">LD C,E</abbr></td>
    <td><abbr title="Copy H to C">LD C,H</abbr></td>
    <td><abbr title="Copy L to C">LD C,L</abbr></td>
    <td><abbr title="Copy value pointed by HL to C">LD C,(HL)</abbr></td>
    <td><abbr title="Copy A to C">LD C,A</abbr></td>
    <td><abbr title="Copy B to D">LD D,B</abbr></td>
    <td><abbr title="Copy C to D">LD D,C</abbr></td>
    <td><abbr title="Copy D to D">LD D,D</abbr></td>
    <td><abbr title="Copy E to D">LD D,E</abbr></td>
    <td><abbr title="Copy H to D">LD D,H</abbr></td>
    <td><abbr title="Copy L to D">LD D,L</abbr></td>
    <td><abbr title="Copy value pointed by HL to D">LD D,(HL)</abbr></td>
    <td><abbr title="Copy A to D">LD D,A</abbr></td>
    <td><abbr title="Copy B to E">LD E,B</abbr></td>
    <td><abbr title="Copy C to E">LD E,C</abbr></td>
    <td><abbr title="Copy D to E">LD E,D</abbr></td>
    <td><abbr title="Copy E to E">LD E,E</abbr></td>
    <td><abbr title="Copy H to E">LD E,H</abbr></td>
    <td><abbr title="Copy L to E">LD E,L</abbr></td>
    <td><abbr title="Copy value pointed by HL to E">LD E,(HL)</abbr></td>
    <td><abbr title="Copy A to E">LD E,A</abbr></td>
    <td><abbr title="Copy B to H">LD H,B</abbr></td>
    <td><abbr title="Copy C to H">LD H,C</abbr></td>
    <td><abbr title="Copy D to H">LD H,D</abbr></td>
    <td><abbr title="Copy E to H">LD H,E</abbr></td>
    <td><abbr title="Copy H to H">LD H,H</abbr></td>
    <td><abbr title="Copy L to H">LD H,L</abbr></td>
    <td><abbr title="Copy value pointed by HL to H">LD H,(HL)</abbr></td>
    <td><abbr title="Copy A to H">LD H,A</abbr></td>
    <td><abbr title="Copy B to L">LD L,B</abbr></td>
    <td><abbr title="Copy C to L">LD L,C</abbr></td>
    <td><abbr title="Copy D to L">LD L,D</abbr></td>
    <td><abbr title="Copy E to L">LD L,E</abbr></td>
    <td><abbr title="Copy H to L">LD L,H</abbr></td>
    <td><abbr title="Copy L to L">LD L,L</abbr></td>
    <td><abbr title="Copy value pointed by HL to L">LD L,(HL)</abbr></td>
    <td><abbr title="Copy A to L">LD L,A</abbr></td>
    <td><abbr title="Copy B to address pointed by HL">LD (HL),B</abbr></td>
    <td><abbr title="Copy C to address pointed by HL">LD (HL),C</abbr></td>
    <td><abbr title="Copy D to address pointed by HL">LD (HL),D</abbr></td>
    <td><abbr title="Copy E to address pointed by HL">LD (HL),E</abbr></td>
    <td><abbr title="Copy H to address pointed by HL">LD (HL),H</abbr></td>
    <td><abbr title="Copy L to address pointed by HL">LD (HL),L</abbr></td>
    <td><abbr title="Halt processor">HALT</abbr></td>
    <td><abbr title="Copy A to address pointed by HL">LD (HL),A</abbr></td>
    <td><abbr title="Copy B to A">LD A,B</abbr></td>
    <td><abbr title="Copy C to A">LD A,C</abbr></td>
    <td><abbr title="Copy D to A">LD A,D</abbr></td>
    <td><abbr title="Copy E to A">LD A,E</abbr></td>
    <td><abbr title="Copy H to A">LD A,H</abbr></td>
    <td><abbr title="Copy L to A">LD A,L</abbr></td>
    <td><abbr title="Copy value pointed by HL to A">LD A,(HL)</abbr></td>
    <td><abbr title="Copy A to A">LD A,A</abbr></td>
    <td><abbr title="Add B to A">ADD A,B</abbr></td>
    <td><abbr title="Add C to A">ADD A,C</abbr></td>
    <td><abbr title="Add D to A">ADD A,D</abbr></td>
    <td><abbr title="Add E to A">ADD A,E</abbr></td>
    <td><abbr title="Add H to A">ADD A,H</abbr></td>
    <td><abbr title="Add L to A">ADD A,L</abbr></td>
    <td><abbr title="Add value pointed by HL to A">ADD A,(HL)</abbr></td>
    <td><abbr title="Add A to A">ADD A,A</abbr></td>
    <td><abbr title="Add B and carry flag to A">ADC A,B</abbr></td>
    <td><abbr title="Add C and carry flag to A">ADC A,C</abbr></td>
    <td><abbr title="Add D and carry flag to A">ADC A,D</abbr></td>
    <td><abbr title="Add E and carry flag to A">ADC A,E</abbr></td>
    <td><abbr title="Add H and carry flag to A">ADC A,H</abbr></td>
    <td><abbr title="Add and carry flag L to A">ADC A,L</abbr></td>
    <td><abbr title="Add value pointed by HL and carry flag to A">ADC A,(HL)</abbr></td>
    <td><abbr title="Add A and carry flag to A">ADC A,A</abbr></td>
    <td><abbr title="Subtract B from A">SUB A,B</abbr></td>
    <td><abbr title="Subtract C from A">SUB A,C</abbr></td>
    <td><abbr title="Subtract D from A">SUB A,D</abbr></td>
    <td><abbr title="Subtract E from A">SUB A,E</abbr></td>
    <td><abbr title="Subtract H from A">SUB A,H</abbr></td>
    <td><abbr title="Subtract L from A">SUB A,L</abbr></td>
    <td><abbr title="Subtract value pointed by HL from A">SUB A,(HL)</abbr></td>
    <td><abbr title="Subtract A from A">SUB A,A</abbr></td>
    <td><abbr title="Subtract B and carry flag from A">SBC A,B</abbr></td>
    <td><abbr title="Subtract C and carry flag from A">SBC A,C</abbr></td>
    <td><abbr title="Subtract D and carry flag from A">SBC A,D</abbr></td>
    <td><abbr title="Subtract E and carry flag from A">SBC A,E</abbr></td>
    <td><abbr title="Subtract H and carry flag from A">SBC A,H</abbr></td>
    <td><abbr title="Subtract and carry flag L from A">SBC A,L</abbr></td>
    <td><abbr title="Subtract value pointed by HL and carry flag from A">SBC A,(HL)</abbr></td>
    <td><abbr title="Subtract A and carry flag from A">SBC A,A</abbr></td>
    <td><abbr title="Logical AND B against A">AND B</abbr></td>
    <td><abbr title="Logical AND C against A">AND C</abbr></td>
    <td><abbr title="Logical AND D against A">AND D</abbr></td>
    <td><abbr title="Logical AND E against A">AND E</abbr></td>
    <td><abbr title="Logical AND H against A">AND H</abbr></td>
    <td><abbr title="Logical AND L against A">AND L</abbr></td>
    <td><abbr title="Logical AND value pointed by HL against A">AND (HL)</abbr></td>
    <td><abbr title="Logical AND A against A">AND A</abbr></td>
    <td><abbr title="Logical XOR B against A">XOR B</abbr></td>
    <td><abbr title="Logical XOR C against A">XOR C</abbr></td>
    <td><abbr title="Logical XOR D against A">XOR D</abbr></td>
    <td><abbr title="Logical XOR E against A">XOR E</abbr></td>
    <td><abbr title="Logical XOR H against A">XOR H</abbr></td>
    <td><abbr title="Logical XOR L against A">XOR L</abbr></td>
    <td><abbr title="Logical XOR value pointed by HL against A">XOR (HL)</abbr></td>
    <td><abbr title="Logical XOR A against A">XOR A</abbr></td>
    <td><abbr title="Logical OR B against A">OR B</abbr></td>
    <td><abbr title="Logical OR C against A">OR C</abbr></td>
    <td><abbr title="Logical OR D against A">OR D</abbr></td>
    <td><abbr title="Logical OR E against A">OR E</abbr></td>
    <td><abbr title="Logical OR H against A">OR H</abbr></td>
    <td><abbr title="Logical OR L against A">OR L</abbr></td>
    <td><abbr title="Logical OR value pointed by HL against A">OR (HL)</abbr></td>
    <td><abbr title="Logical OR A against A">OR A</abbr></td>
    <td><abbr title="Compare B against A">CP B</abbr></td>
    <td><abbr title="Compare C against A">CP C</abbr></td>
    <td><abbr title="Compare D against A">CP D</abbr></td>
    <td><abbr title="Compare E against A">CP E</abbr></td>
    <td><abbr title="Compare H against A">CP H</abbr></td>
    <td><abbr title="Compare L against A">CP L</abbr></td>
    <td><abbr title="Compare value pointed by HL against A">CP (HL)</abbr></td>
    <td><abbr title="Compare A against A">CP A</abbr></td>
    <td><abbr title="Return if last result was not zero">RET NZ</abbr></td>
    <td><abbr title="Pop 16-bit value from stack into BC">POP BC</abbr></td>
    <td><abbr title="Absolute jump to 16-bit location if last result was not zero">JP NZ,nn</abbr></td>
    <td><abbr title="Absolute jump to 16-bit location">JP nn</abbr></td>
    <td><abbr title="Call routine at 16-bit location if last result was not zero">CALL NZ,nn</abbr></td>
    <td><abbr title="Push 16-bit BC onto stack">PUSH BC</abbr></td>
    <td><abbr title="Add 8-bit immediate to A">ADD A,n</abbr></td>
    <td><abbr title="Call routine at address 0000h">RST 0</abbr></td>
    <td><abbr title="Return if last result was zero">RET Z</abbr></td>
    <td><abbr title="Return to calling routine">RET</abbr></td>
    <td><abbr title="Absolute jump to 16-bit location if last result was zero">JP Z,nn</abbr></td>
    <td><abbr title="Extended operations (two-byte instruction code)">Ext ops</abbr></td>
    <td><abbr title="Call routine at 16-bit location if last result was zero">CALL Z,nn</abbr></td>
    <td><abbr title="Call routine at 16-bit location">CALL nn</abbr></td>
    <td><abbr title="Add 8-bit immediate and carry to A">ADC A,n</abbr></td>
    <td><abbr title="Call routine at address 0008h">RST 8</abbr></td>
    <td><abbr title="Return if last result caused no carry">RET NC</abbr></td>
    <td><abbr title="Pop 16-bit value from stack into DE">POP DE</abbr></td>
    <td><abbr title="Absolute jump to 16-bit location if last result caused no carry">JP NC,nn</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Call routine at 16-bit location if last result caused no carry">CALL NC,nn</abbr></td>
    <td><abbr title="Push 16-bit DE onto stack">PUSH DE</abbr></td>
    <td><abbr title="Subtract 8-bit immediate from A">SUB A,n</abbr></td>
    <td><abbr title="Call routine at address 0010h">RST 10</abbr></td>
    <td><abbr title="Return if last result caused carry">RET C</abbr></td>
    <td><abbr title="Enable interrupts and return to calling routine">RETI</abbr></td>
    <td><abbr title="Absolute jump to 16-bit location if last result caused carry">JP C,nn</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Call routine at 16-bit location if last result caused carry">CALL C,nn</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Subtract 8-bit immediate and carry from A">SBC A,n</abbr></td>
    <td><abbr title="Call routine at address 0018h">RST 18</abbr></td>
    <td><abbr title="Save A at address pointed to by (FF00h + 8-bit immediate)">LDH (n),A</abbr></td>
    <td><abbr title="Pop 16-bit value from stack into HL">POP HL</abbr></td>
    <td><abbr title="Save A at address pointed to by (FF00h + C)">LDH (C),A</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Push 16-bit HL onto stack">PUSH HL</abbr></td>
    <td><abbr title="Logical AND 8-bit immediate against A">AND n</abbr></td>
    <td><abbr title="Call routine at address 0020h">RST 20</abbr></td>
    <td><abbr title="Add signed 8-bit immediate to SP">ADD SP,d</abbr></td>
    <td><abbr title="Jump to 16-bit value pointed by HL">JP (HL)</abbr></td>
    <td><abbr title="Save A at given 16-bit address">LD (nn),A</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Logical XOR 8-bit immediate against A">XOR n</abbr></td>
    <td><abbr title="Call routine at address 0028h">RST 28</abbr></td>
    <td><abbr title="Load A from address pointed to by (FF00h + 8-bit immediate)">LDH A,(n)</abbr></td>
    <td><abbr title="Pop 16-bit value from stack into AF">POP AF</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="DIsable interrupts">DI</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Push 16-bit AF onto stack">PUSH AF</abbr></td>
    <td><abbr title="Logical OR 8-bit immediate against A">OR n</abbr></td>
    <td><abbr title="Call routine at address 0030h">RST 30</abbr></td>
    <td><abbr title="Add signed 8-bit immediate to SP and save result in HL">LDHL SP,d</abbr></td>
    <td><abbr title="Copy HL to SP">LD SP,HL</abbr></td>
    <td><abbr title="Load A from given 16-bit address">LD A,(nn)</abbr></td>
    <td><abbr title="Enable interrupts">EI</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Operation removed in this CPU">XX</abbr></td>
    <td><abbr title="Compare 8-bit immediate against A">CP n</abbr></td>
    <td><abbr title="Call routine at address 0038h">RST 38</abbr></td>
"""
