output = ""
for pixel in range(0,256):
	row = ""
	for BGP in range(0,256):
		result = (BGP >> (2*pixel)) & 0x3
		if result == 0:
			 result = 255
		elif result == 1:
			 result = 192
		elif result == 2: 
			 result = 96
		elif result == 3:
			 result = 0
		row+= "0x%02X,"%result
	row = "{" + row[:-1] + "},"
	output += row + "\n"

print "/* array autogenerated by Utilities/getPixelColourLookup.py */"
print "{ %s }"%output
